[platformio]
src_dir = ./yoRadio/src
data_dir = ./yoRadio/data

[env:esp32-s3-n16r8]
lib_extra_dirs = ./
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM14
monitor_port = COM14
monitor_speed = 115200
build_flags =
	-DCORE_DEBUG_LEVEL=1	; Set to 0 for no debug; saves memory / 5 for full debug
  -DTEST_BOARD
; ESP32-S3 info from: https://github.com/sivar2311/ESP32-S3-PlatformIO-Flash-and-PSRAM-configurations
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.extra_flags = 
  -DBOARD_HAS_PSRAM

; required libraries - you may need to edit this list! put universal libs here and build-dependent libs below... also notes are here.
lib_deps =
  bblanchon/ArduinoJson@^6.21.3
  ;crankyoldgit/IRremoteESP8266 @ ^2.8.6
  adafruit/Adafruit GFX Library@^1.11.9
  adafruit/Adafruit BusIO@^1.14.5
  ;adafruit/Adafruit SSD1306@^2.5.13 ; Tiny OLED
  ; olikraus/U8g2 @ ^2.34.22
  ; with ILI9488 you don't need this external library...?
  ;adafruit/Adafruit ILI9488 ; Big SPI display (untested)

[env:self-contained-oled-remote]
lib_extra_dirs = ./
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM14
monitor_port = COM14
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DSELF_CONTAINED_OLED_REMOTE
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.extra_flags = 
  -DBOARD_HAS_PSRAM
lib_deps =
  ${env:esp32-s3-n16r8.lib_deps}
  adafruit/Adafruit SH110X@^2.1.11 ; OLED

[env:ali-speaker-oled]
lib_extra_dirs = ./
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM14
monitor_port = COM14
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DALI_SPEAKER_OLED
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.extra_flags = 
  -DBOARD_HAS_PSRAM
lib_deps =
  ${env:esp32-s3-n16r8.lib_deps}
    adafruit/Adafruit SH110X@^2.1.11 ; OLED

[env:ali-speaker-color]
lib_extra_dirs = ./
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM14
monitor_port = COM14
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DALI_SPEAKER_COLOR
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.extra_flags = 
  -DBOARD_HAS_PSRAM
lib_deps =
  ${env:esp32-s3-n16r8.lib_deps}
  adafruit/Adafruit ST7735 and ST7789 Library@^1.10.4 ; SPI TFT (Red Board, probably others) * must

[env:ali-speaker-bigscreen]
lib_extra_dirs = ./
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM14
monitor_port = COM14
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DALI_SPEAKER_BIGSCREEN
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.extra_flags = 
  -DBOARD_HAS_PSRAM
lib_deps =
  ${env:esp32-s3-n16r8.lib_deps}
