name: Sync Dev Branch

on:
  workflow_dispatch:

jobs:
  sync-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Create or update dev branch
        run: |
          # Switch to main branch first
          git checkout main
          
          # Reset dev branch to main (create if doesn't exist, reset if it does)
          git checkout -B dev
          git reset --hard main

          # Apply changes from trip5 branch (excluding config files)
          git checkout trip5 -- .
          
          # Remove the configuration files that shouldn't be in PRs
          git rm -f yoRadio/mytheme.h yoRadio/myoptions.h platformio.ini TRIP5NOTES.txt || true
          
          # Remove custom workflow files specific to this fork
          git rm -f .github/workflows/sync-dev-branch.yml .github/workflows/platformio-trip5-builds.yml || true

          # Commit the changes
          git add -A
          git commit -m "Apply Trip5 changes (exclude config files)" || echo "No changes to commit"

          # Push to dev branch
          git push origin dev --force
